//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FAA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseHistory
    {
        public int CHID { get; set; }
        public int CourseNo { get; set; }
        public string Description { get; set; }
        public System.DateTime ChangeDate { get; set; }
    
        public virtual Course Course { get; set; }
    }
}
