//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FAA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PCN_Audit
    {
        public Nullable<int> PCNID { get; set; }
        public string Activity { get; set; }
        public string DoneBy { get; set; }
        public string Description { get; set; }
        public System.DateTime Date_Time { get; set; }
    }
}
